[server]
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501

[theme]
primaryColor = "#F39C12"
backgroundColor = "#000000"
secondaryBackgroundColor = "#333333"
textColor = "#FFFFFF"
